### PR TITLE
Improved DaemonCLI compatibility with Click decorators

### PR DESCRIPTION
**Pull request by lemon24**
... so you can write code like:

``` python
@click.command(cls=DaemonCLI)
@pass_daemon
@click.pass_context
def main(context, daemon):
    print "look ma, I have a context:", context
    while True:
        ...
```

### CODE REVIEW

**Comment by jnrbsn** [comment]
First, sorry for the extremely delayed response.

I'm not necessarily against the change itself, but honestly, I don't like the way you organized the tests. I've been meaning to write a bunch of tests, but I have very specific ideas in mind for how I want to organize them. I don't really know what to suggest. It feels wrong to ask you to remove the tests, but I guess that's what I'm getting at.

**Comment by lemon24** [comment]
Done. No problem, I mostly included them to prove that my changes didn't break stuff. Thanks for being straightforward about it.

**Comment by k1-hedayati** [comment]
@jnrbsn It would be great if you could merge this because today I couldn't find a way to do self-reload with click integration, in order to reload daemon you should have `daemon` object in worker method I don't know how pass it when I'm using it with click.

**Comment by jnrbsn** [comment]
@k1-hedayati: The `pass_daemon` decorator already exists in the `daemonocle.cli` module.

@lemon24: I'm still interested in this change, but I want to first come up with a better way to pass arguments to the worker function in general.

**Pull request closed without merging**
